spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/wechat?characterEncoding=utf8&serverTimezone=Asia/Shanghai
      username: 17860760376
      password: hq1437186643
      max-active: 20
      max-wait: 6000
      min-idle: 1
      test-on-borrow: true
      test-on-return: true
mybatis:
  mapper-locations: classpath*:com/bobo/mapper/*Mapper.xml
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    com.bobo.mapper: debug
